import type { Request, Response } from "express";
import { createRequire } from "node:module";
// Generated by the build:vercel script and bundled with this Function.
const require = createRequire(import.meta.url);
const serverBundle = require("../.vercel-build/server.cjs");
const { createApp } = serverBundle as typeof import("../server.ts");

const appPromise = createApp({ serveFrontend: false });

export default async function handler(req: Request, res: Response) {
  const app = await appPromise;
  return app(req, res);
}
